# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/api/': # Isso cobre todas as rotas
#             allow_origin: ['http://191.232.244.118:5173']
#             allow_headers: ['Content-Type', 'Authorization']
#             allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#             max_age: 3600

####ALTERAÇÊOS DOCKER AUZRE#####
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With'] # Adicione X-Requested-With se necessário
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # Aplica a todos os paths sob /api/
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Pode redefinir se necessário
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
