controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
api_attendant_login:
    path: /api/attendant/login
    controller: App\Controller\AttendantAuthController::login
    methods: [POST]