apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atendimento-ingress
  namespace: atendimento
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - helpdesk.pgmbh.org
      secretName: supp-pgmbh-tls-secret
  rules:
    - host: helpdesk.pgmbh.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webserver
                port:
                  number: 80
