apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: helpdesk
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mailhog
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailhog
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mailhog
    spec:
      containers:
        - image: mailhog/mailhog
          name: prod-mailhog-appservice
      restartPolicy: Always
